### ISSUE TITLE
Missing support for Gradle v4.1

### ISSUE THREAD

**Issue by loxal** [melix/jmh-gradle-plugin#105]
On Windows, with plugin version 0.4.4, Gradle 4.1, and OpenJDK (not Oracle JDK!) I get:

```
Caused by: org.gradle.api.GradleException: Error during execution of benchmarks
        at me.champeau.gradle.IsolatedRunner.run(IsolatedRunner.java:40)
        at org.gradle.workers.internal.WorkerServer.execute(WorkerServer.java:31)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:38)
        at org.gradle.workers.internal.WorkerDaemonServer.execute(WorkerDaemonServer.java:25)
        at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:98)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:146)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:128)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        ... 3 more
Caused by: No benchmarks to run; check the include/exclude regexps.
        at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:261)
        at org.openjdk.jmh.runner.Runner.run(Runner.java:206)
        at me.champeau.gradle.IsolatedRunner.run(IsolatedRunner.java:38)
        ... 12 more

```

**Comment by lyrachord** [comment]
Me too.
4.1 Oracle-JDK-1.8-144
Windows\Lock?
StackOverflow someone hint admin, not works
put -DignoreLock=true option not works, seems gradle no pass into the runner fork?

Fighting

**Comment by lyrachord** [comment]
> Caused by: No benchmarks to run; check the include/exclude regexps.

It's indicates jmh config in gradle is wrong
apply plugin: 'me.champeau.gradle.jmh'
`
jmh {
    include = 'som\\..*Bench.*'
`
it's regex

**Comment by lyrachord** [comment]
jmh gradle runner seems pure, just pass options

I dead doubt there is some issue from gradle fork.

C:\Windows\/jmh.lock<==System.getProperty("java.io.tempdir")+"/jmh.lock")
Maybe some thing change java.io.tempdir to /, it's system root, in windows it's c:\windows, AYK
I try to search gradle src, nothing got althrough there are methods such as getTempDir, ?setTempDir
Sigh!

If temp is set to /, Wow, No more imagination

**Comment by melix** [comment]
Do you happen to have a test project which would allow me reproduce this? I'm no Windows user, but I'd like to find out if the issue is _Windows_, or if the issue is different. I, for one, tried to run this plugin on 4.1 +OpenJDK without any problem, but I'm on Linux...

**Comment by loxal** [comment]
@melix sure, check out https://github.com/loxal/muctool

**Comment by melix** [comment]
Alright, I can reproduce the `No benchmarks to run; check the include/exclude regexps.` error on Linux, with your test project. I get it both with OpenJDK and OracleJDK.

I also get this error with Gradle 4.0 and 4.1, so I think it's unrelated, but experiments show it must not be the [regex problem](https://github.com/lyrachord) either. I'll keep you in touch.

**Comment by BrainStone** [comment]
I'm getting the lock error on the Windows PowerShell with Gradle 4.1. Worked fine with Gradle 4.0

**Comment by loxal** [comment]
I just switched to Gradle 4.0.2 and everything went fine without any adjustments, just as described [here](https://discuss.gradle.org/t/jmh-task-run-from-buildship-fails-to-acquire-jmh-lock-works-fine-from-shell/23642/5).

Apparently
```
jmh {
   jvmArgs = ['-Djmh.ignoreLock=true']
//...
}
```
could solve the problem but it is ignored on Windows.

**Comment by corneil** [comment]
I have a project that worked fine with 0.3.1 plugin on gradle 3.x when moving to 0.4.3 with gradle 4.1 the windows lock message appeared.
[https://github.com/corneil/compare-fp](https://github.com/corneil/compare-fp)

**Comment by wrprice** [comment]
I had to go up to Gradle 4.3.1 and plugin 0.4.5-beta-2 to run on Windows.
