### ISSUE TITLE
Unable to use JDK preview features

### ISSUE THREAD

**Issue by gwinstanley** [melix/jmh-gradle-plugin#190]
**Describe the bug**
When trying to benchmark code making use of JDK preview features, the plugin fails due to the byte code generator being called without the appropriate JVM arguments being applied.

**To Reproduce**
1. Enable preview features on suitably recent JDK
2. Write/run benchmark
3. See error

The compile tasks & jmh DSL section configured including these:
```
tasks.withType(JavaCompile) {
  options.compilerArgs += [ '--enable-preview' ]
}
jmh {
	jvmArgs = [ '--enable-preview' ]
	//...
}
```

The resulting error is predictably relating to class version, which implies the JVM arguments configured in the DSL are not being applied to the byte code generator JVM when it is forked:
```
Exception in thread "main" java.lang.UnsupportedClassVersionError: Preview features are not enabled for foo/Benchmark$Context (class file version 59.65535). Try running with '--enable-preview'
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
        at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:825)
        at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:723)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:646)
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:604)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:576)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:468)
        at org.openjdk.jmh.generators.bytecode.JmhBytecodeGenerator.main(JmhBytecodeGenerator.java:90)
```

**Comment by SirYwell** [comment]
You can add jvm arguments that way:
```groovy
jmhRunBytecodeGenerator {
    getJvmArgs().add("--enable-preview")
}
```
(I didn't test that exactly, but that works for incubator modules at least)

**Comment by gwinstanley** [comment]
@SirYwell Problem solved; many thanks.

**Comment by LeoFuso** [comment]
The suggested answer didn't work for me, the problem was in the `compileJmhJava` task also, 

```groovy
compileJmhJava {
    options.compilerArgs += ['--enable-preview', '--add-modules', 'jdk.incubator.vector']
}

jmhRunBytecodeGenerator {
    jvmArgs.add '--add-modules=jdk.incubator.vector'
}
```
