### ISSUE TITLE
Build fails if sub project applies idea plugin but root project does not.

### ISSUE THREAD

**Issue by rvail** [melix/jmh-gradle-plugin#32]
Perhaps we have an unusual setup but our root project does not apply the idea plugin but it is applied to our sub projects.
The following exception is thrown when running any gradle task.
<pre><code>
Caused by: org.gradle.api.internal.MissingMethodException: Could not find method idea() for arguments [me.champeau.gradle.JMHPlugin$_apply_closure5_closure15@16d98aed] on root project 'my_project'.
	at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:68)
	at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:56)
	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:172)
	at org.gradle.api.internal.project.DefaultProject_Decorated.invokeMethod(Unknown Source)
	at me.champeau.gradle.JMHPlugin$_apply_closure5.doCall(JMHPlugin.groovy:96)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:83)
	at org.gradle.listener.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
	at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy12.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:79)
	... 38 more
</code></pre>

**Comment by bensteinert** [comment]
Hi rvail, 
I can reproduce the behavior with 0.1.3 but not with 0.2.0. 

which version do you use? Currently released 0.1.3? Please try new 0.2.0-SNAPSHOT from repository. It contains fixes regarding gradle project access behavior. Newer version should also be available soon. 
Cheers
Ben

**Comment by rvail** [comment]
I use 0.1.3 and just confirmed that it is fixed in the latest version.
