### ISSUE TITLE
Issue with benchmarkMode? 

### ISSUE THREAD

**Issue by srangwal** [melix/jmh-gradle-plugin#73]
When I use 
```
  benchmarkMode = ['thrpt','ss']
```

I get 
```
Exception in thread "main" java.lang.IllegalStateException: Unable to parse benchmark mode: "[thrpt"
Known values are [Throughput/thrpt, AverageTime/avgt, SampleTime/sample, SingleShotTime/ss, All/all]
	at org.openjdk.jmh.annotations.Mode.deepValueOf(Mode.java:124)
	at org.openjdk.jmh.runner.options.CommandLineOptions.<init>(CommandLineOptions.java:314)
	at org.openjdk.jmh.Main.main(Main.java:41)
```

**Comment by aalmiray** [comment]
Fixed with #74
