### ISSUE TITLE
Exception in jmhJar when using test sourceSet

### ISSUE THREAD

**Issue by mipmapman** [melix/jmh-gradle-plugin#79]
I'm using version 0.3.0 of jmh-gradle-plugin in a Gradle 2.13 build.

I've encountered a problem where the build fails unless I have a `src/test/resources` folder in existence and containing at least one file. For the moment I've created a `src/test/resources` folder and populated with it a dummy text file. It would be nice not to have this workaround though.

I've had a quick look at the source but am lost in the world of Gradle code. To be honest I'm not even sure if what I'm trying to do is valid in the world of Gradle or if it is a bug in Gradle and not the JMH plugin.

I've created a simple project here which demonstrates the issue I am facing:

[https://github.com/mipmapman/bar](https://github.com/mipmapman/bar)

Note that it occurs because I have the following:

```
dependencies {
    jmh sourceSets.test.output
}
```

I need this because my benchmark code extends/makes use of my test code. I am using this because even if I use the following in the JMH config without the above dependency line, I can't get past the compilation stage:

`includeTests = true`

When I run:

`gradle clean jmhJar`

I get the exception listed below.

As mentioned, to workaround this if I add a `src/test/resources` folder with a dummy file then the build works fine...

I'm struggling to see how I can specify to just use the compiled test classes and not expect test resources when stating:

```
dependencies {
    jmh sourceSets.test.output
}
```

---

```
:clean
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestJava
:processTestResources UP-TO-DATE
:testClasses
:compileJmhJava
:processJmhResources UP-TO-DATE
:jmhClasses
:jmhRunBytecodeGenerator
Processing 1 classes from /Users/nick/Documents/Personal/projects/tsl8r/bar/build/classes/jmh with "reflection" generator
Writing out Java source to /Users/nick/Documents/Personal/projects/tsl8r/bar/build/jmh-generated-sources and resources to /Users/nick/Documents/Personal/projects/tsl8r/bar/build/jmh-generated-classes
:jmhCompileGeneratedClasses
:jmhJar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jmhJar'.
> Cannot expand ZIP '/Users/nick/Documents/Personal/projects/tsl8r/bar/build/resources/test' as it does not exist.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jmhJar'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.InvalidUserDataException: Cannot expand ZIP '/Users/nick/Documents/Personal/projects/tsl8r/bar/build/resources/test' as it does not exist.
    at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:66)
    at org.gradle.api.internal.file.collections.FileTreeAdapter.visit(FileTreeAdapter.java:109)
    at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl.visit(AbstractFileTree.java:141)
    at org.gradle.api.internal.file.CompositeFileTree.visit(CompositeFileTree.java:58)
    at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpecActionImpl.java:37)
    at org.gradle.api.internal.file.copy.CopySpecActionImpl.execute(CopySpecActionImpl.java:24)
    at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecResolver.walk(DefaultCopySpec.java:498)
    at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecResolver.walk(DefaultCopySpec.java:500)
    at org.gradle.api.internal.file.copy.DefaultCopySpec$DefaultCopySpecResolver.walk(DefaultCopySpec.java:500)
    at org.gradle.api.internal.file.copy.DefaultCopySpec.walk(DefaultCopySpec.java:322)
    at org.gradle.api.internal.file.copy.CopySpecBackedCopyActionProcessingStream.process(CopySpecBackedCopyActionProcessingStream.java:36)
    at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator$1.process(DuplicateHandlingCopyActionDecorator.java:44)
    at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator$1.process(NormalizingCopyActionDecorator.java:56)
    at org.gradle.api.internal.file.archive.ZipCopyAction$1.execute(ZipCopyAction.java:64)
    at org.gradle.api.internal.file.archive.ZipCopyAction$1.execute(ZipCopyAction.java:62)
    at org.gradle.internal.IoActions.withResource(IoActions.java:74)
    at org.gradle.api.internal.file.archive.ZipCopyAction.execute(ZipCopyAction.java:62)
    at org.gradle.api.internal.file.copy.NormalizingCopyActionDecorator.execute(NormalizingCopyActionDecorator.java:52)
    at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator.execute(DuplicateHandlingCopyActionDecorator.java:42)
    at org.gradle.api.internal.file.copy.CopyActionExecuter.execute(CopyActionExecuter.java:38)
    at org.gradle.api.tasks.AbstractCopyTask.copy(AbstractCopyTask.java:83)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 14 more

```

**Comment by ivansenic** [comment]
Hi,

I have the same problem and I am not even changing the dependencies of the jmh configuration, but my testCompile:

{code}
dependencies {
	testCompile project(':inspectit.shared.all').sourceSets.test.output
}
{code}

Any idea why?

**Comment by swpalmer** [comment]
I get the same issue.  It seems to be caused by the duplication strategy used to unzip the artifacts:

Execution failed for task ':jmhJar'.
> Could not expand ZIP 'C:\Users\scott.palmer\.gradle\caches\modules-2\files-2.1\org.hamcrest\hamcrest-core\1.1\860340562250678d1a344907ac75754e259cdb14\hamcrest-core-1.1.jar'.

...
Caused by: org.gradle.api.file.DuplicateFileCopyingException: Encountered duplicate path "org/hamcrest/BaseDescription.class" during copy operation configured with DuplicatesStrategy.FAIL
        at org.gradle.api.internal.file.copy.DuplicateHandlingCopyActionDecorator$1$1.processFile(DuplicateHandlingCopyActionDecorator.java:53)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.processFile(CopyFileVisitorImpl.java:60)
        at org.gradle.api.internal.file.copy.CopyFileVisitorImpl.visitFile(CopyFileVisitorImpl.java:44)
        at org.gradle.api.internal.file.AbstractFileTree$FilteredFileTreeImpl$1.visitFile(AbstractFileTree.java:150)
        at org.gradle.api.internal.file.archive.ZipFileTree.visit(ZipFileTree.java:91)
        ... 85 more

**Comment by vyazelenko** [comment]
The duplicateStrategy can be changed in the build as described in the README, e.g.:
```gradle
jmh {
  duplicateClassesStrategy = 'warn'
}
```

**Comment by harrydentCA** [comment]
Try adding:

```
jmhJar.doFirst {
    new File("build/resources/core").mkdirs()
}
```

**Comment by mipmapman** [comment]
```
jmhJar.doFirst {
    new File("build/resources/test").mkdirs()
}

```
@harrydentCA good workaround - thanks.
