### ISSUE TITLE
Unable to run JMH benchmarks

### ISSUE THREAD

**Issue by sergey-morenets** [melix/jmh-gradle-plugin#90]
Hi

I created new Gradle project, created src/jmh/java folder and put one class with benchmark operations. This class works fine with JMH Maven plugin. However when I run "gradle jmh" command for this project I get error message: "No matching benchmarks. Miss-spelled regexp?"

Here is my build.gradle:

`
plugins {
  id "me.champeau.gradle.jmh" version "0.3.1"
}

apply plugin: 'java'

repositories {
    mavenLocal()
    
    mavenCentral()
}

dependencies {
    jmh 'org.openjdk.jmh:jmh-core:1.18'
    jmh 'org.openjdk.jmh:jmh-generator-annprocess:1.18'
}

jmh {
    iterations = 10
    fork = 1
    jvmArgs = '-server'
    timeUnit = 'ns'
    warmupIterations =10
    jmhVersion = '1.18'
    benchmarkMode = ['avgt'] 
    duplicateClassesStrategy = 'warn'
}
`

Thanks.

**Comment by aalmiray** [comment]
What's the output when running `gradle jmh -S`?

**Comment by sergey-morenets** [comment]
:compileJava NO-SOURCE
:processResources NO-SOURCE
:classes UP-TO-DATE
:compileTestJava NO-SOURCE
:processTestResources NO-SOURCE
:testClasses UP-TO-DATE
:compileJmhJava UP-TO-DATE
:processJmhResources NO-SOURCE
:jmhClasses UP-TO-DATE
:jmhRunBytecodeGenerator UP-TO-DATE
:jmhCompileGeneratedClasses UP-TO-DATE
:jmhJar UP-TO-DATE
:jmh
No matching benchmarks. Miss-spelled regexp?
Use EXTRA verbose mode to debug the pattern matching.
:jmh FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jmh'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_121\bin\java.exe'' finished w
ith non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':jmh'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.exec
ute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execut
e(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecu
ter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskE
xecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter
.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execut
e(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter
.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.ex
ecute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
skWorker$1.execute(DefaultTaskGraphExecuter.java:236)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
skWorker$1.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:61)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
skWorker.execute(DefaultTaskGraphExecuter.java:228)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTa
skWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.processTask(AbstractTaskPlanExecutor.java:77)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorW
orker.run(AbstractTaskPlanExecutor.java:58)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(Defaul
tTaskPlanExecutor.java:32)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(Defau
ltTaskGraphExecuter.java:113)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTask
ExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExec
uter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecu
ter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildEx
ecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecute
r.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execut
e(DefaultGradleLauncher.java:256)
        at org.gradle.initialization.DefaultGradleLauncher$RunTasksAction.execut
e(DefaultGradleLauncher.java:253)
        at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(Defaul
tBuildOperationExecutor.java:56)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(Default
GradleLauncher.java:175)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradle
Launcher.java:119)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLaun
cher.java:102)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildControl
ler.java:71)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(Exe
cuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildA
ctionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProce
ssBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.ex
ecute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.ex
ecute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter
.execute(ServicesSetupBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter
.execute(ServicesSetupBuildActionExecuter.java:31)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBu
ild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
CommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(
WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute
(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.
execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
ardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(Forw
ardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(For
wardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogA
ndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClien
t.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
CommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBu
ild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(Build
CommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(
DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.
run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(Daemon
StateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.
onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableE
xecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.
java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor
.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.gradle.process.internal.ExecException: Process 'command 'C:\Progr
am Files\Java\jdk1.8.0_121\bin\java.exe'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNo
rmalExitValue(DefaultExecHandle.java:369)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJava
ExecAction.java:31)
        at org.gradle.api.tasks.JavaExec.exec(JavaExec.java:74)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore
$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore
$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore
$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
ctTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(Abstra
ctTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.ex
ecuteActions(ExecuteActionsTaskExecuter.java:76)
        ... 73 more


BUILD FAILED

**Comment by sergey-morenets** [comment]
Hi @aalmiray 

Any updates? I compared jars, generated by Maven plugin and your plugin and the issue is that there is two BenchmarkList files in the META-INF folder: valid and empty one. If remove empty file then I can successfully execute benchmarks: java -jar benchmars-jmh.jar

I also noticed that this happened because BenchmarkList file is in two locations:
1) build\classes\jmh\META-INF\  - that's where valid file sits
2) build\jmh-generated-classes\META-INF\ - that's where empty file sits

Thanks!

**Comment by vyazelenko** [comment]
@sergey-morenets This seems to be the same issue as described in #88

**Comment by vyazelenko** [comment]
@sergey-morenets @aalmiray There is also a hint in #88 that this could be related to the new Gradle version (i.e. > 2.14).

**Comment by sergey-morenets** [comment]
@vyazelenko Thank you, if I downgrade to Gradle 2.14, my jmh execution works properly.
@aalmiray Since Gradle 3.0 was released for a while(in August 2016) do you have any plans to support it?

**Comment by maffelbaffel** [comment]
Had the same problem.
Possbile workaround:
Deleting that additional `BenchmarkList`:
````
task deleteEmptyBmList(type: Delete) {
    delete "$buildDir/jmh-generated-classes/META-INF/BenchmarkList"
}
jmhCompileGeneratedClasses.finalizedBy deleteEmptyBmList
````
This seems to work for me 👍

**Comment by sergey-morenets** [comment]
Thank you, @maffelbaffel 

That works for me as well.

**Comment by rvit34** [comment]
Reproduced the bug at plugin 0.4.5 and Gradle 4.5.1 
After a build is done I see only one and not empty `BenchmarkList` at `build/jmh-generated-classes/META-INF/` and fail with message 
`Execution failed for task ':jmh'.
> A failure occurred while executing me.champeau.gradle.IsolatedRunner
   > ERROR: Unable to find the resource: /META-INF/BenchmarkList
`

**Comment by skjolber** [comment]
I get this problem when running with JDK 11 on the latest Gradle (5.2.1) and plugin version

**Comment by EugeneLesnov** [comment]
any solution ?

**Comment by Mart-Bogdan** [comment]
According to   https://stackoverflow.com/a/56043252/716769
Making fields not readonly was disable since JDK12. But proided answer with lookup works.

I've downloaded this plugin locally and added following code:
```java
final class FieldHelper {

    private static final VarHandle MODIFIERS;

    static {
        try {
            MethodHandles.Lookup lookup = MethodHandles.privateLookupIn(Field.class, MethodHandles.lookup());
            MODIFIERS = lookup.findVarHandle(Field.class, "modifiers", int.class);
        } catch (IllegalAccessException | NoSuchFieldException ex) {
            throw new RuntimeException(ex);
        }
    }

    public static void makeNonFinal(Field field) {
        int mods = field.getModifiers();
        if (Modifier.isFinal(mods)) {
            MODIFIERS.set(field, mods & ~Modifier.FINAL);
        }
    }
}
```
```java
    private static void makeWriteable(Field listField) throws NoSuchFieldException, IllegalAccessException {
        listField.setAccessible(true);
        FieldHelper.makeNonFinal(listField);
    }
```
and it seems working.

Full git diff:
```diff
diff --git a/build.gradle.kts b/build.gradle.kts
index af9b013..7cc784d 100644
--- a/build.gradle.kts
+++ b/build.gradle.kts
@@ -86,9 +86,9 @@ tasks {
 }
 
 java {
-    toolchain {
-        languageVersion.set(JavaLanguageVersion.of(8))
-    }
+//    toolchain {
+//        languageVersion.set(JavaLanguageVersion.of(8))
+//    }
     withSourcesJar()
     withJavadocJar()
 }
diff --git a/src/main/groovy/me/champeau/gradle/IsolatedRunner.java b/src/main/groovy/me/champeau/gradle/IsolatedRunner.java
index 14d9488..1dc3d36 100644
--- a/src/main/groovy/me/champeau/gradle/IsolatedRunner.java
+++ b/src/main/groovy/me/champeau/gradle/IsolatedRunner.java
@@ -24,6 +24,8 @@ import org.openjdk.jmh.runner.options.Options;
 
 import javax.inject.Inject;
 import java.io.File;
+import java.lang.invoke.MethodHandles;
+import java.lang.invoke.VarHandle;
 import java.lang.reflect.Field;
 import java.lang.reflect.Modifier;
 import java.util.Set;
@@ -57,6 +59,7 @@ public class IsolatedRunner implements Runnable {
         updateCompilerHints();
         try {
             System.setProperty("java.class.path", toPath(classpathUnderTest));
+
             // JMH uses the system property java.class.path to derive the runtime classpath of the forked JVM
             runner.run();
         } catch (RunnerException e) {
@@ -83,9 +86,7 @@ public class IsolatedRunner implements Runnable {
 
     private static void makeWriteable(Field listField) throws NoSuchFieldException, IllegalAccessException {
         listField.setAccessible(true);
-        Field modifiersField = Field.class.getDeclaredField("modifiers");
-        modifiersField.setAccessible(true);
-        modifiersField.setInt(listField, listField.getModifiers() & ~Modifier.FINAL);
+        FieldHelper.makeNonFinal(listField);
     }
 
     private void tryUpdateFieldViaReflection(Class<?> clazz, Object target, String fieldName, Object value) {
@@ -110,3 +111,24 @@ public class IsolatedRunner implements Runnable {
         return sb.toString();
     }
 }
+final class FieldHelper {
+
+    private static final VarHandle MODIFIERS;
+
+    static {
+        try {
+            MethodHandles.Lookup lookup = MethodHandles.privateLookupIn(Field.class, MethodHandles.lookup());
+            MODIFIERS = lookup.findVarHandle(Field.class, "modifiers", int.class);
+        } catch (IllegalAccessException | NoSuchFieldException ex) {
+            throw new RuntimeException(ex);
+        }
+    }
+
+    public static void makeNonFinal(Field field) {
+        int mods = field.getModifiers();
+        if (Modifier.isFinal(mods)) {
+            MODIFIERS.set(field, mods & ~Modifier.FINAL);
+        }
+    }
+
+}
\ No newline at end of file
```

But this isn't ready fix as this would break jdk8 compatibility

**Comment by Mart-Bogdan** [comment]
This code won't compile on JDK8 so we need to make some trick during build process to build two versions of reflection code.


P.S. Perhaps patch could be made to JMH repo to add proper constructor arguments for **org.openjdk.jmh.runner.Runner** so there won't be need to use reflection?

**Comment by ephemient** [comment]
Couldn't https://github.com/melix/mrjar-gradle be used to provide Java separate <14/≥14 implementations?

**Comment by melix** [comment]
Would you mind trying the latest release? I've completely changed how it integrates JMH.

**Comment by ephemient** [comment]
> Would you mind trying the latest release? I've completely changed how it integrates JMH.

Oh, I hadn't checked for new releases. I had to adjust my build scripts, but it does seem to work with Gradle 6.8.3, me.champeau.jmh 0.6.2, and OpenJDK 11 and 15.

However, I'm no longer getting any visible output; there's nothing printed for the whole JMH run.
