### ISSUE TITLE
Benchmarks fail to run when not inside a package

### ISSUE THREAD

**Issue by DSteve595** [melix/jmh-gradle-plugin#91]
If I have a benchmark in the `src/main/java` directory (not in a package), such as `src/main/java/Test.java`, then I get the following error when running `gradle jmh`:

```
:jmhRunBytecodeGenerator
Processing 2 classes from C:\*path*\build\classes\jmh with "reflection" generator
Writing out Java source to C:\*path*\build\jmh-generated-sources and resources to C:\*path*\build\jmh-generated-classes
Annotation generator had thrown the exception.
java.lang.NullPointerException
	at org.openjdk.jmh.generators.reflection.RFClassInfo.getPackageName(RFClassInfo.java:51)
	at org.openjdk.jmh.generators.core.BenchmarkGenerator.validateBenchmark(BenchmarkGenerator.java:243)
	at org.openjdk.jmh.generators.core.BenchmarkGenerator.generate(BenchmarkGenerator.java:90)
	at org.openjdk.jmh.generators.bytecode.JmhBytecodeGenerator.main(JmhBytecodeGenerator.java:100)


:jmhRunBytecodeGenerator FAILED
```

If I move that file into a package, making it `src/main/java/apackage/Test.java`, it compiles and benchmarks as expected.

**Comment by vyazelenko** [comment]
@DSteve595 this is not a problem with a plugin but rather with JMH. It seems that benchmarks with default package are not supported when byte code generator is used.

**Comment by cbeams** [comment]
This issue just caught me too. Thanks @DSteve595 for posting the fix!
